# Especifica la versión de Node.js a utilizar (opcional)
[build.environment]
  NODE_VERSION = "14"

# Configura la ruta al directorio de construcción
[build]
  publish = "dist"  # Reemplaza "dist" con la carpeta correcta de tu proyecto

# Configura los comandos de construcción (si es necesario)
[build]
  command = "npm run build"  # Cambia esto a tu comando de construcción

# Configura la versión de Netlify y otras opciones (opcional)
[build]
  base = ""  # Ruta base del proyecto (si es necesario)


